# Generated by Django 4.2.23 on 2025-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('game', models.CharField(default='Tic-Tac-Toe', max_length=50)),
                ('difficulty', models.CharField(max_length=10)),
                ('score', models.IntegerField(default=1)),
                ('date_achieved', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
