# Generated by Django 4.2.23 on 2025-08-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='game',
            field=models.CharField(default='Tic-Tac-Toe', max_length=50),
        ),
        migrations.AddField(
            model_name='highscore',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
